FROM node:alpine as builder

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

WORKDIR /app

# add app
COPY . .

RUN yarn install && yarn build 

# nginx state for serving content
FROM nginx:alpine

COPY templates /etc/nginx/templates/

# Copy static assets from builder stage
COPY --from=builder /app/build /usr/share/nginx/html
