version: "3"
services:
  api1:
    build:
      context: ../StoreService
      dockerfile: ../Docker/Dockerfile.backend
    ports: 
      - 8000:8000
    depends_on:
      - frontend
  api2:
    build:
      context: ../RetrieveService
      dockerfile: ../Docker/Dockerfile.backend
    ports: 
      - 8001:8000
    depends_on:
      - frontend
  frontend:
    image: ghcr.io/brunosbastos/es_tdg/frontend
    environment:
      - HOST_NAME=ec2-18-215-185-124.compute-1.amazonaws.com
    ports:
      - 80:80
    
