version: "3"
services:
  api1:
    build:
      context: ../StoreService
      dockerfile: ../Docker/Dockerfile.backend
    ports: 
      - 8000:8000
  api2:
    build:
      context: ../RetrieveService
      dockerfile: ../Docker/Dockerfile.backend
    ports: 
      - 8001:8000
  api3:
    build:
      context: ../TemplateFillingService
      dockerfile: ../Docker/Dockerfile.backend
    ports: 
      - 8002:8000
  frontend:
    image: ghcr.io/brunosbastos/es_tdg/frontend:latest
    links:
      - api1
      - api2
      - api3
    environment:
      - HOST_NAME=18.215.185.124
    ports:
      - 80:80
    
