name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        echo $DOCKER_PASSWORD | docker login https://ghcr.io -u BrunosBastos --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd frontend/
        yarn install && yarn build
        sudo docker build -f Dockerfile.frontend -t ghcr.io/brunosbastos/es_tdg/frontend .
        sudo docker push ghcr.io/brunosbastos/es_tdg/frontend

