name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd frontend/
        yarn install && yarn build
        sudo docker build -f Dockerfile.frontend -t ghcr.io/brunosbastos/es_tdg/frontend .
        sudo docker push ghcr.io/brunosbastos/es_tdg/frontend

